development:
  clients:
    default:
      database: risk2210_development
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false
    scope_overwrite_exception: false
    use_utc: true
test:
  clients:
    default:
      database: risk2210_test
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false
    scope_overwrite_exception: false
    use_utc: true
production:
  clients:
    default:
      database: risk2210_production
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false
    scope_overwrite_exception: false
    use_utc: true
