earth = Map.find_or_create_by(:name => "Earth")
Continent.find_or_create_by(map_id: earth.id, name: "North America", type: "Land", bonus: 5, color: "#eae74a")
Continent.find_or_create_by(map_id: earth.id, name: "South America", type: "Land", bonus: 2, color: "#d2a32d")
Continent.find_or_create_by(map_id: earth.id, name: "Africa", type: "Land", bonus: 3, color: "#64b2d6")
Continent.find_or_create_by(map_id: earth.id, name: "Asia", type: "Land", bonus: 7, color: "#7cc446")
Continent.find_or_create_by(map_id: earth.id, name: "Europe", type: "Land", bonus: 5, color: "#9e51a3")
Continent.find_or_create_by(map_id: earth.id, name: "Australia", type: "Land", bonus: 2, color: "#e63629")
Continent.find_or_create_by(map_id: earth.id, name: "US Pacific", type: "Water", bonus: 2, color: "#92c8e0")
Continent.find_or_create_by(map_id: earth.id, name: "Asia Pacific", type: "Water", bonus: 1, color: "#d1dc38")
Continent.find_or_create_by(map_id: earth.id, name: "North Atlantic", type: "Water", bonus: 2, color: "#ef4f1b")
Continent.find_or_create_by(map_id: earth.id, name: "South Atlantic", type: "Water", bonus: 1, color: "#79c139")
Continent.find_or_create_by(map_id: earth.id, name: "Indian", type: "Water", bonus: 2, color: "#f27115")

moon = Map.find_or_create_by(:name => "Moon", :moon => true)
Continent.find_or_create_by(map_id: moon.id, name: "Sajon", type: "Lunar", bonus: 4, color: "#96ca8c")
Continent.find_or_create_by(map_id: moon.id, name: "Cresinion", type: "Lunar", bonus: 2, color: "#f79063")
Continent.find_or_create_by(map_id: moon.id, name: "Delphot", type: "Lunar", bonus: 2, color: "#7073c0")

mars = Map.find_or_create_by(:name => "Mars")
Continent.find_or_create_by(map_id: mars.id, name: "Arcadia", type: "Land", bonus: 3, color: "#df9ce9")
Continent.find_or_create_by(map_id: mars.id, name: "Amazonis", type: "Land", bonus: 6, color: "#7e83de")
Continent.find_or_create_by(map_id: mars.id, name: "Tharsis", type: "Land", bonus: 3, color: "#f0e660")
Continent.find_or_create_by(map_id: mars.id, name: "Vulcan", type: "Land", bonus: 5, color: "#e76263")
Continent.find_or_create_by(map_id: mars.id, name: "Eden", type: "Land", bonus: 4, color: "#6df25b")
Continent.find_or_create_by(map_id: mars.id, name: "Casius", type: "Land", bonus: 5, color: "#71d0e8")
Continent.find_or_create_by(map_id: mars.id, name: "Propontis", type: "Water", bonus: 2, color: "#8dd92f")
Continent.find_or_create_by(map_id: mars.id, name: "Acidalium", type: "Water", bonus: 3, color: "#f0fb71")
Continent.find_or_create_by(map_id: mars.id, name: "Arabia", type: "Water", bonus: 2, color: "#12bcf0")
Continent.find_or_create_by(map_id: mars.id, name: "Utopia", type: "Water", bonus: 2, color: "#e417ff")
Continent.find_or_create_by(map_id: mars.id, name: "Isidis", type: "Water", bonus: 1, color: "#e99127")

mars_moons = Map.find_or_create_by(:name => "Phobos & Deimos", :moon => true)
Continent.find_or_create_by(map_id: mars_moons.id, name: "Norseland", type: "Lunar", bonus: 3, color: "#f27f43")
Continent.find_or_create_by(map_id: mars_moons.id, name: "New America", type: "Lunar", bonus: 2, color: "#8ffd76")
Continent.find_or_create_by(map_id: mars_moons.id, name: "Federation", type: "Lunar", bonus: 3, color: "#dd81ee")

asteroids = Map.find_or_create_by(:name => "Asteroid Colonies", :moon => true)
Continent.find_or_create_by(map_id: asteroids.id, name: "1 Ceres", type: "Lunar", bonus: 4, color: "#e87386")
Continent.find_or_create_by(map_id: asteroids.id, name: "4 Vesta", type: "Lunar", bonus: 2, color: "#9aea89")
Continent.find_or_create_by(map_id: asteroids.id, name: "Dactyl", type: "Lunar", bonus: 1, color: "#80ccf1")
Continent.find_or_create_by(map_id: asteroids.id, name: "243 Ida", type: "Lunar", bonus: 2, color: "#f0f47b")

io = Map.find_or_create_by(:name => "Io")
Continent.find_or_create_by(map_id: io.id, name: "Narkom", type: "Land", bonus: 4, color: "#718cc1")
Continent.find_or_create_by(map_id: io.id, name: "Automin", type: "Land", bonus: 5, color: "#e35b5b")
Continent.find_or_create_by(map_id: io.id, name: "Skandi", type: "Land", bonus: 2, color: "#0e0e0e")
Continent.find_or_create_by(map_id: io.id, name: "Balt", type: "Land", bonus: 3, color: "#e2d66a")
Continent.find_or_create_by(map_id: io.id, name: "Ugricya", type: "Land", bonus: 5, color: "#78a07d")
Continent.find_or_create_by(map_id: io.id, name: "Hoenheim", type: "Land", bonus: 5, color: "#d087e0")
Continent.find_or_create_by(map_id: io.id, name: "Ecclesia", type: "Land", bonus: 2, color: "#9eddef")
Continent.find_or_create_by(map_id: io.id, name: "Ghaul", type: "Land", bonus: 4, color: "#aaf982")
Continent.find_or_create_by(map_id: io.id, name: "Granada", type: "Land", bonus: 2, color: "#bc8372")
Continent.find_or_create_by(map_id: io.id, name: "Mashriq", type: "Water", bonus: 1, color: "#bfbfbf")
Continent.find_or_create_by(map_id: io.id, name: "Caprica", type: "Water", bonus: 1, color: "#fd9415")
Continent.find_or_create_by(map_id: io.id, name: "Soter", type: "Water", bonus: 1, color: "#2e2e2e")
Continent.find_or_create_by(map_id: io.id, name: "Khell", type: "Water", bonus: 3, color: "#6bc2cb")
Continent.find_or_create_by(map_id: io.id, name: "Nuraghe", type: "Water", bonus: 1, color: "#e10005")
Continent.find_or_create_by(map_id: io.id, name: "Magreb", type: "Water", bonus: 3, color: "#4c0fb5")

europa = Map.find_or_create_by(:name => "Europa")
Continent.find_or_create_by(map_id: europa.id, name: "Angeln", type: "Land", bonus: 3, color: "#d896dd")
Continent.find_or_create_by(map_id: europa.id, name: "Galilei", type: "Land", bonus: 6, color: "#141414")
Continent.find_or_create_by(map_id: europa.id, name: "Seaxna", type: "Land", bonus: 3, color: "#e8df78")
Continent.find_or_create_by(map_id: europa.id, name: "Cymru", type: "Land", bonus: 4, color: "#b2ecf7")
Continent.find_or_create_by(map_id: europa.id, name: "Byfed", type: "Land", bonus: 2, color: "#a3f674")
Continent.find_or_create_by(map_id: europa.id, name: "Avalon", type: "Land", bonus: 3, color: "#ff777b")
Continent.find_or_create_by(map_id: europa.id, name: "SungTzu", type: "Water", bonus: 2, color: "#ee0613")
